authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import VRegister, logout_session, login_session
from django.conf import settings
from django.conf.urls.static import static

app_name = "authentication"

urlpatterns = [
   
    path("register/", VRegister.as_view(), name="authentication"),
    path("login/", login_session, name="login"),
    path("logout/", logout_session, name="logout"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from. import views

urlpatterns = [
    path("", views.blog, name="blog"),
    path("category/<int:category_id>/", views.category, name="category"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name="home"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

magia_calzados/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("authentication/", include("authentication.urls")),
    path("services/", include("services.urls")),
    path("shop/", include("shop.urls")),
    path("contact/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("shopping_cart/", include("shopping_cart.urls")),
    path('', include("core.urls"))
    
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    
    USERNAME_FIELD="email"
    REQUIRED_FIELDS=['username']

core/views.py
from django.shortcuts import render, HttpResponse
from django.conf import settings
# Create your views here.

def home(request):
    app_name = settings.APP_SHOW_NAME
    return render(request, 'core/home.html', {'app_name': app_name})

core/templates/core/base.html
<html>
    <head>
    {% load static %}



    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">



     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'core/css/gestion.css'%}" rel="stylesheet">
</head>

<body>


  <!-- Offcanvas -->
  <div id="sidebar" class="offcanvas offcanvas-start">
    <div class="offcanvas-header">
      {% if user.is_authenticated %}
        <h5 class="font-weight-bold font-weight-bolder">  Bienvenido {{user.username}}</h5>
        {% else %}
        <h5 class="font-weight-bold font-weight-bolder">  Bienvenido </h5>
      {% endif %}
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
      
    </div>
    <div class="offcanvas-body">
      <!-- Enlaces del menú lateral -->
      <ul class="navbar-nav mx-auto flex-column">
        <li class="nav-item {% if request.path == '/' %} active {%endif%} px-lg-4">
          <a class="nav-link text-uppercase text-expanded" href="{% url 'home'%}">Inicio</a>
        </li>
        <li class="nav-item {% if request.path == '/services/' %} active {%endif%} px-lg-4">
          <a class="nav-link text-uppercase text-expanded" href="{% url 'services'%}">Servicios</a>
        </li>
        <li class="nav-item {% if request.path == '/shop/' %} active {%endif%} px-lg-4">
          <a class="nav-link text-uppercase text-expanded" href="{% url 'shop'%}">Tienda</a>
        </li>
        <li class="nav-item {% if request.path == '/contact/' %} active {%endif%}m px-lg-4">
          <a class="nav-link text-uppercase text-expanded" href="{% url 'contact'%}">Contacto</a>
        </li>
        <li class="nav-item {% if request.path|slice:':6' == '/blog/' %} active {%endif%} px-lg-4">
          <a class="nav-link text-uppercase text-expanded" href="{% url 'blog'%}">Blog</a>
        </li>
       
      </ul>
    </div>

    <div class="offcanvas-footer p-3">
      <ul class="list-unstyled">
      {% if user.is_authenticated %}          
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'authentication:logout'%}">Cerrar sesión</a>
            </li>
            
            {% else %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'authentication:login'%}">Iniciar sesión</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'authentication:authentication'%}">Registrarse</a>
            </li>
            {% endif %}
      </ul>
    </div>
  </div>


  

 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
   <div style="padding: 0 0 0 10px;">
    <button class="btn btn-outline-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar" aria-controls="sidebar">
      <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
      </svg>
    </button>
   </div>
  <div class="container">
    <div style="width: 100%; ">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-flex align-items-center my-auto mx-auto" href="">
        <span class="mx-auto">{{app_name}}</span>
      </a>
    </div>
  </div>
</nav>



 

  
    {% block content %}
    {% endblock %}

  
    {% block message %}
    {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; {{app_name}}</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    

</body>


</html>

core/templates/core/home.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/principal.jpg'%}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block message %}
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

   