authentication/urls.py
from django.contrib import admin
from django.urls import path
from .views import VRegister, logout_session, login_session
from django.conf import settings
from django.conf.urls.static import static

app_name = "authentication"

urlpatterns = [
   
    path("register/", VRegister.as_view(), name="authentication"),
    path("login/", login_session, name="login"),
    path("logout/", logout_session, name="logout"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from. import views

urlpatterns = [
    path("", views.blog, name="blog"),
    path("category/<int:category_id>/", views.category, name="category"),
    
]

magia_calzados/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("authentication/", include("authentication.urls")),
    path("services/", include("services.urls")),
    path("shop/", include("shop.urls")),
    path("contact/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("shopping_cart/", include("shopping_cart.urls")),
    path('', include("core.urls"))
    
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.shop, name="shop"),
    path('product/<int:id>', views.details, name="product_detail")
    
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shopping_cart"

urlpatterns = [
    path("add/<int:product_id>", views.add_product, name="add"),
    path("delete/<int:product_id>", views.delete_product, name="delete"),
    path("subtract/<int:product_id>", views.subtract_product, name="subtract"),
    path("clear/", views.clear_cart, name="clear"),
    
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse
# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nombre")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")

    class Meta:
        verbose_name = "Categoría de producto"
        verbose_name_plural = "Categorías de productos"

    def __str__(self):
        return self.name
    


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name="Nombre")
    description = models.TextField(verbose_name="Descripción")
    price = models.DecimalField(verbose_name="Precio", decimal_places=2, max_digits=10, validators=[MinValueValidator(0)])
    stock = models.IntegerField(verbose_name="Stock", validators=[MinValueValidator(0)])
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name="Categoría")
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    
    @property
    def get_first_specifications(self):
        return FirstProductSpecification.objects.filter(product=self)
    
    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])
        

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.name
    
   
class FirstProductSpecification(models.Model):
    data = models.CharField(max_length = 100, verbose_name="Información")
    stock = models.IntegerField(verbose_name="Stock", validators=[MinValueValidator(0)])
    price = models.DecimalField(verbose_name="Precio", max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Producto")
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    
    @property
    def get_second_specifications(self):
        return SecondProductSpecification.objects.filter(first_spec=self)
    
    def __str__(self):
        return "Producto: %s Especificación: %s"%(self.product.name, self.data)
    
    class Meta:
        verbose_name = "Especificación de producto"
        verbose_name_plural = "Especificaciones de productos"
        
class SecondProductSpecification(models.Model):
    data = models.CharField(max_length = 100, verbose_name="Información")
    stock = models.IntegerField(verbose_name="Stock", validators=[MinValueValidator(0)])
    price = models.DecimalField(verbose_name="Precio", max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    first_spec = models.ForeignKey(FirstProductSpecification, on_delete=models.CASCADE, verbose_name="Producto")
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    
    def __str__(self):
        return "%s Extra: %s"%(self.first_spec.__str__, self.data)
    
    class Meta:
        verbose_name = "Especificación extra de producto"
        verbose_name_plural = "Especificaciones extra de productos" 
        
        
    
class ProductImage(models.Model):
    image = models.ImageField(upload_to="products/", verbose_name="Imagen")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Producto", null=True, blank=True)
    first = models.ForeignKey(FirstProductSpecification, on_delete=models.CASCADE, verbose_name="Especificación", null=True, blank=True)
    
    class Meta:
        verbose_name = "Imagen de producto"
        verbose_name_plural = "Imagenes de productos"
        
    def __str__(self):
        feat = "None"
        if self.first:
            feat = self.first.data
        return "imagen de -> producto: %s, especificación: %s"%(self.product.name, feat)
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from shop.models import ProductCategory, Product, ProductImage, FirstProductSpecification

# Create your views here.


def shop(request):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    for product in products:
        first_spec = FirstProductSpecification.objects.filter(product=product).first()
        images = list(ProductImage.objects.filter(Q(product=product) | Q(first=first_spec)))
        if len(images) > 0:
            product.image = images[0]
    
    return render(request, 'shop/shop.html', {'categories': categories, 'products': products})

def details(request, id):
    product = get_object_or_404(Product, pk=id)
    print(product)
    first_spec = FirstProductSpecification.objects.filter(product=product).first()
    images = list(ProductImage.objects.filter(Q(product=product) | Q(first=first_spec)))
    if len(images) > 0:
        product.images = images
    return render(request, 'shop/details.html', {'product': product})

shop/templates/shop/details.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
     
<div id="carouselExampleIndicators" class="carousel slide" style="width: 50%; height:50%; align-items: center; margin: auto;" >
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">

        {% for image in product.images%}
            <div class="carousel-item active">
            <img src="{{ image.image.url }}" class="d-block w-100" alt="..." style="width: 75%; height:100%;">
            </div>
        
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

        
{% endblock %}

shop/templates/shop/shop.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
      {% if products|length > 0 %}
      <div class="container" style="width:100%; padding: 10px;">
            {% if user.is_authenticated %}
            <div style="float:right;">

                  {%include "cart/widget.html" %}
            </div>

            {% endif %}

            <div class="row">
                  {% for product in products %}

                  <div class="col-md-4">
                        <a href="{{ product.get_absolute_url }}">
                        <div class="card" style="width: 100%;">
                                    <div>
                                    <img class="card-img-top" src="{{ product.image.image.url }}" alt="" style="height:250px;">
                                    <div class="card-body" style="text-align: center; height:150px;">
                                          <h7 style="font-weight: bold;">{{ product.name }}</h7>
                                          <p class="card-text">{{ product.description }}</p>
                                          <p class="card-text">{{ product.price }}€</p>
                                    </div>
                              </div>
                                    <div class="card-footer text-center">
                                          {% if user.is_authenticated %}
                                          <a href="{% url 'shopping_cart:add' product.id %}" class="btn btn-success">Agregar al carro</a>
                                          
                                          {% else %}
                                          <a href="{% url 'authentication:login' %}" class="btn btn-success">Iniciar sesión para comprar</a>
                                          {% endif %}
                                    </div>
                              </div>
                        </a>
            
                  </div>

            {% endfor %}

            </div>
      </div>

           

            <section>
                  <div style="width: 75%; margin:auto; text-align: center; color: white;"> 
                        Categorías:

                        {% for category in categories %}
                              <p>{{category}}</p>
                        {%endfor%}
                  
                  </div>
            </section>

      {% else %}
      <section>
            <div style="width: 75%; margin:auto; text-align: center; color: white;"> 
                  No hay productos
            
            </div>
      </section>
      {% endif %}
        
{% endblock %}